/**
 * sanctions.ts
 *
 * Offline OFAC SDN sanctions check for Ethereum addresses.
 *
 * Loads the embedded sanctions.json snapshot at import time and exposes
 * a synchronous `checkSanctions()` function. No network calls, zero latency.
 *
 * Scope: US Treasury OFAC SDN list, "Digital Currency Address - ETH" entries
 * ONLY. EU and UN lists are NOT included. This is a baseline, not a
 * replacement for the on-chain layers.
 *
 * The JSON is generated by `scripts/sync-lists.ts` and updated automatically
 * by the GitHub Action in `.github/workflows/sync-sanctions.yml` (weekly).
 *
 * Usage:
 * ```ts
 * import { checkSanctions, preflight } from 'arc-preflight'
 *
 * // preflight() already runs this as its first layer. Call it directly when
 * // you want a synchronous, RPC-free answer (e.g. form validation).
 * if (checkSanctions(recipient)) {
 *   throw new Error('Recipient is on the OFAC SDN list')
 * }
 * ```
 *
 * @see https://ofac.treasury.gov/specially-designated-nationals-list-data-formats-data-schema
 */

// Use a relative JSON import — tsup handles JSON bundling automatically
import sanctionsJson from '../data/sanctions.json' with { type: 'json' }

type SanctionsData = {
  version: string
  source: string
  scope?: string
  description: string
  count: number
  addresses: string[]
}

const data = sanctionsJson as SanctionsData

// Build a Set<lowercase address> for O(1) lookups
const SANCTIONS_SET = new Set<string>(
  data.addresses.map((a) => a.toLowerCase()),
)

/**
 * Checks whether an Ethereum address appears on the embedded OFAC SDN snapshot.
 *
 * Scope: OFAC SDN "Digital Currency Address - ETH" entries only — not EU, not
 * UN, not Arc's own additions. Purely offline: no network call, no async.
 *
 * Returns `true` if the address is sanctioned; `false` otherwise.
 *
 * ⚠️  This check is a supplement to, not a replacement for, the on-chain
 * `preflight()` layers. Arc's runtime blocklist and the OFAC SDN list are
 * related but not identical.
 *
 * @param address - Ethereum address to check (checksummed or lowercase)
 */
export function checkSanctions(address: string): boolean {
  if (!address || typeof address !== 'string') return false
  return SANCTIONS_SET.has(address.toLowerCase())
}

/**
 * The OFAC publication date of the embedded sanctions snapshot (YYYY-MM-DD).
 */
export const sanctionsVersion: string = data.version

/**
 * Total number of Ethereum addresses in the embedded snapshot.
 */
export const sanctionsCount: number = data.count

/**
 * Human-readable scope statement for the embedded snapshot.
 */
export const sanctionsScope: string =
  data.scope ?? 'OFAC SDN Digital Currency Address - ETH only'
