/**
 * sanctions.ts
 *
 * Offline OFAC sanctions check for Ethereum addresses.
 *
 * Loads the embedded sanctions.json snapshot at import time and exposes
 * a synchronous `checkSanctions()` function. No network calls, zero latency.
 *
 * The JSON is generated by `scripts/sync-lists.ts` and updated automatically
 * by the GitHub Action in `.github/workflows/sync-sanctions.yml`.
 *
 * Usage:
 * ```ts
 * import { checkSanctions, preflight } from 'arc-preflight'
 *
 * // Recommended pattern: check sanctions first (free), then probe on-chain
 * if (checkSanctions(recipient)) {
 *   throw new Error('Recipient is on OFAC sanctions list')
 * }
 * const result = await preflight(sender, recipient, client)
 * ```
 *
 * @see https://ofac.treasury.gov/specially-designated-nationals-list-data-formats-data-schema
 */

// Use a relative JSON import — tsup handles JSON bundling automatically
import sanctionsJson from '../data/sanctions.json' with { type: 'json' }

type SanctionsData = {
  version: string
  source: string
  description: string
  count: number
  addresses: string[]
}

const data = sanctionsJson as SanctionsData

// Build a Set<lowercase address> for O(1) lookups
const SANCTIONS_SET = new Set<string>(
  data.addresses.map((a) => a.toLowerCase()),
)

/**
 * Checks whether an Ethereum address appears on the OFAC SDN sanctions list.
 *
 * This is a purely offline check — no network call, no async. The sanctions
 * data is embedded in the package and updated periodically via GitHub Action.
 *
 * Returns `true` if the address is sanctioned; `false` otherwise.
 *
 * ⚠️  This check is a supplement to, not a replacement for, the `preflight()`
 * eth_call probe. Arc's on-chain blocklist and the OFAC SDN list are related
 * but not identical. Use both for maximum coverage.
 *
 * @param address - Ethereum address to check (checksummed or lowercase)
 */
export function checkSanctions(address: string): boolean {
  if (!address || typeof address !== 'string') return false
  return SANCTIONS_SET.has(address.toLowerCase())
}

/**
 * The OFAC publication date of the embedded sanctions snapshot (YYYY-MM-DD).
 */
export const sanctionsVersion: string = data.version

/**
 * Total number of Ethereum addresses in the embedded snapshot.
 */
export const sanctionsCount: number = data.count
